import "./globals.css";
// <Header /> is removed.
// {children} is modified to <body>{children}</body>
// Reference:
import type { Metadata } from "next";
//TODO: 전역 폰트 재설정(Inter, NotoSansKR)
import { Inter } from "next/font/google";
import HeaderNav from "./component/HeaderNav";
import FooterNav from "./component/FooterNav";
import Link from "next/link";
import Image from "next/image";
import ToTop from "./component/ToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        {/* //TODO: 현재 루트에서 나누고 있는데, 재고필요, 공통 객체만 남겨둘 것 footer분리 */}
        <HeaderNav />
        <ToTop />
        <div>{children}</div>
        <footer className="mb-[75px]">
          <div className="footerbox">
            <ul className="terms">
              <li>
                <Link href={""}>서비스 이용약관</Link>
              </li>
              <li>
                <Link href={""}>개인정보 처리방침</Link>
              </li>
              {/* 개인정보 처리방침: red */}
            </ul>

            <div className="info">
              <p>신세계포인트 고객센터</p>
              <button>1899-4349</button>
              <p>
                운영시간<span>:</span>
                <em>09</em>시 - <em>18</em>시<br />
                점심시간<span>:</span>
                <em>12</em>시 - <em>13</em>시<br />
                (공휴일 제외)
              </p>
            </div>

            <div className="txt_cnt">
              <p>
                <span>㈜이마트 서울시 중구 세종대로 7길 37(순화동)</span>
                <span>대표자: 강희석</span>
                <span>사업자등록번호 : 206-86-50913</span>
              </p>
              <p>COPYRIGHT (c) EMART INC. ALL RIGHTS RESERVED.</p>
            </div>

            <div className="watermark">
              <Link href={""}>
                <Image
                  src="/images/wa_mark.144ed89e.png"
                  width={67}
                  height={46}
                  // fill={true}
                  alt=""
                ></Image>
              </Link>
            </div>
          </div>
        </footer>
        <FooterNav />
      </body>
    </html>
  );
}
